// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtujsvzfthsqfeqrsqvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0dWpzdnpmdGhzcWZlcXJzcXZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NjA2MDIsImV4cCI6MjA2NzIzNjYwMn0.qY8HTnkhM0osSaYmw7EWE8EfB6g3RQCbSkeU16n2arU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});